strategy:
  matrix:
    linux:
      vmImage: ubuntu-latest
    macos:
      vmImage: windows-latest
    windows:
      vmImage: macOS-latest
pool:
  vmImage: $(vmImage)
steps:
- task: InstallMATLAB@1
- task: RunMATLABBuild@1
  inputs:
    tasks: test
