jobs:
  - job: Run_MATLAB_Build
    strategy:
      matrix:
        linux:
          vmImage: ubuntu-22.04
        macos:
          vmImage: macOS-latest
        windows:
          vmImage: windows-latest
    pool:
      vmImage: $(vmImage)
    steps:
    - task: InstallMATLAB@1
    - task: RunMATLABBuild@1
      inputs:
        tasks: test
