version: 2.1
orbs:
  matlab: mathworks/matlab@1.3.0
  codecov: codecov/codecov@1.2.0
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests: 
          code-coverage-cobertura: coverage.xml
      - codecov/upload: 
          file: coverage.xml
