version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  my-job:    
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests
workflows:
  test:
    jobs:
      - my-job
