version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  my-job:    
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-pdf: test-results/results.pdf
          test-results-junit: test-results/results.xml
          code-coverage-html: code-coverage
      - store_artifacts:
          path: test-results/results.pdf
      - store_test_results:
          path: test-results/results.xml
      - store_artifacts:
          path: code-coverage
workflows:
  test:
    jobs:
      - my-job
      
