version: 2.1
orbs:
  matlab: mathworks/matlab@1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  macos:
    macos:
      xcode: 15.3.0
  windows:
    resource_class: "windows.medium"
    machine:
      image: 'windows-server-2022-gui:current'

jobs:
  my-job:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests

workflows:
  test:
    jobs:
      - my-job:
          matrix:
            parameters:
              os: [linux, macos, windows]
