version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  run-matlab-build:    
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install
      - matlab/run-build:
          tasks: mytask
workflows:
  build:
    jobs:
      - run-matlab-build
