version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  my-job:    
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install:
          products: >
            Simulink 
            Simulink_Test 
            Parallel_Computing_Toolbox
      - matlab/run-tests:
          use-parallel: true
workflows:
  build:
    jobs:
      - my-job
