version: 2.1
orbs:
  matlab: mathworks/matlab@1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  windows:
    resource_class: windows.medium
    machine:
      image: windows-server-2022-gui:current
  macos:
    macos:
      xcode: 14.2.0

jobs:
  my-job:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install
      - matlab/run-build:
          tasks: test

workflows:
  build:
    jobs:
      - my-job:
          matrix:
            parameters:
              os: [linux, windows, macos]
