on: [push] # Run workflow on every push
jobs:
  matlab-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
 
      - name: Run build
        uses: matlab-actions/run-build@v2-rc0
